### PR TITLE
Tags Structures with DB functions

### PR DESCRIPTION
**Pull request by mpt777**
I implemented tags on a game with corresponding db methods and routes

### CODE REVIEW

**Comment by mpt777** [comment]
TODO!!!!!!!

case insensitive searching?
Better seed data

query param "tag" -> "tags"

**Comment by jebidiah252** [comment]
@mpt777 it looks like there are some merge conflicts with this PR. If you have some free time, we can meet to work through the merge conflicts and get this merged ASAP.

**Comment by mpt777** [comment]
> @mpt777 it looks like there are some merge conflicts with this PR. If you have some free time, we can meet to work through the merge conflicts and get this merged ASAP.

The conflicts are very minor.
For database.go and mock.go, we can accept the current version of the file. 

For game.go, we need to accept my version of the file as it has the tags attribute of the game struct

**Comment by jebidiah252** [comment]
> 

I think we'll want both for `game.go`

**Comment by mpt777** [comment]
We will want both.
	ID               uuid.UUID
	Title            string
	Description      string
	UserID           uuid.UUID
	VersionNumber    string
	PublishTimestamp string
        Tags                      []string

**Comment by mpt777** [comment]
Do you want to merge them or myself?
Are we comfortable with this plan to keep database and mock, and merge game?

**Comment by jebidiah252** [comment]
I can resolve these conflicts. thank you for helping me out in what we do and don't want.

**Comment by mpt777** [comment]
Thanks for taking care of this!

**Comment by mpt777** [comment]
Merged, now I just need approval

**Review by jebidiah252 — APPROVED** [review]
Looks great! Thanks for making these changes

**Pull request merged**
